# tl-intf-y := tl_intf.o logger_mem.o
# obj-$(CONFIG_HITCHHIKER) += tl-intf.o

hhkr-ctl-y := hhkr_ctl.o hhkr_mempool.o hhkrd_mgmt.o exception_table.o hhkr_secio_driver_el1.o
obj-$(CONFIG_HITCHHIKER) += hhkr-ctl.o